### ISSUE TITLE
Support for Medium sites without medium.com/* domain.

### ISSUE THREAD

**Issue by gonz4lex** [swapagarwal/mediumship#6]
Just wondering if this feature is possible.

For example, https://towardsdatascience.com/ is a Medium publication but the extension does not work in that domain.

**Comment by j3soon** [comment]
Are you using Firefox? I've fixed it in #7

**Comment by swapagarwal** [comment]
We can do something like this:
For URLs like https://towardsdatascience.com/jupyter-is-the-new-excel-a7a22f2fc13a, we can provide a page action which can trigger a refresh with the unlocked story.

**Comment by gonz4lex** [comment]
Hello,

Thanks for your contribution and fixing the issue on FIrefox. However, I am using Chrome and still does not work on the towardsdatascience.com domain, although it does in onezero.medium.com.

Please let me know if there is any information or help I could provide.
Thanks.

**Comment by swapagarwal** [comment]
Hi, the chrome version will be updated sometime today to include this change.

**Comment by saadahmadazad** [comment]
Hi @gonz4lex  @swapagarwal  @j3soon  I am new to opensource community. Will anyone explain me what's happening over there??

**Comment by j3soon** [comment]
Fixed in v2.1 on both browsers.
